export const actionTypes = {
  USER_LOGIN_RES: "USER_LOGIN_RES",
  USER_LOGIN_SUCCEEDED: "USER_LOGIN_SUCCEEDED",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
  USER_REGISTER_RES: "USER_REGISTER_RES",
  USER_REGISTER_SUCCEEDED: "USER_REGISTER_SUCCEEDED",
  USER_REGISTER_FAILED: "USER_REGISTER_FAILED",
};
